/** Stable permission keys used by API and UI. */
export const PlatformPermissions = {
  TENANTS_VIEW: 'platform.tenants.view',
  TENANTS_CREATE: 'platform.tenants.create',
  TENANTS_UPDATE: 'platform.tenants.update',
  TENANTS_SUSPEND: 'platform.tenants.suspend',
  SUBSCRIPTIONS_MANAGE: 'platform.subscriptions.manage',
  USAGE_VIEW: 'platform.usage.view',
  SUPPORT_VIEW: 'platform.support.view',
  SUPPORT_MANAGE: 'platform.support.manage',
  AUDIT_VIEW: 'platform.audit.view',
  SETTINGS_MANAGE: 'platform.settings.manage',
  USERS_MANAGE: 'platform.users.manage',
} as const;

export const TenantPermissions = {
  ORG_BRANCHES_VIEW: 'organization.branches.view',
  ORG_BRANCHES_MANAGE: 'organization.branches.manage',
  ORG_EMPLOYEES_VIEW: 'organization.employees.view',
  ORG_EMPLOYEES_MANAGE: 'organization.employees.manage',
  ORG_ROLES_VIEW: 'organization.roles.view',
  ORG_ROLES_MANAGE: 'organization.roles.manage',
  CRM_CUSTOMERS_VIEW: 'crm.customers.view',
  CRM_CUSTOMERS_CREATE: 'crm.customers.create',
  CRM_CUSTOMERS_UPDATE: 'crm.customers.update',
  CRM_CUSTOMERS_DELETE: 'crm.customers.delete',
  CRM_CUSTOMERS_EXPORT: 'crm.customers.export',
  CRM_ACTIVITIES_MANAGE: 'crm.activities.manage',
  SUPPLIERS_VIEW: 'suppliers.suppliers.view',
  SUPPLIERS_MANAGE: 'suppliers.suppliers.manage',
  SUPPLIERS_RATES_VIEW: 'suppliers.rates.view',
  SUPPLIERS_RATES_MANAGE: 'suppliers.rates.manage',
  SUPPLIERS_RATES_IMPORT: 'suppliers.rates.import',
  QUOTES_RFQ_VIEW: 'quotes.rfq.view',
  QUOTES_RFQ_MANAGE: 'quotes.rfq.manage',
  QUOTES_VIEW: 'quotes.quotes.view',
  QUOTES_CREATE: 'quotes.quotes.create',
  QUOTES_UPDATE: 'quotes.quotes.update',
  QUOTES_APPROVE: 'quotes.quotes.approve',
  QUOTES_DELETE: 'quotes.quotes.delete',
  QUOTES_EXPORT: 'quotes.quotes.export',
  BOOKINGS_VIEW: 'bookings.bookings.view',
  BOOKINGS_CREATE: 'bookings.bookings.create',
  BOOKINGS_UPDATE: 'bookings.bookings.update',
  BOOKINGS_DELETE: 'bookings.bookings.delete',
  SHIPMENTS_VIEW: 'shipments.shipments.view',
  SHIPMENTS_CREATE: 'shipments.shipments.create',
  SHIPMENTS_UPDATE: 'shipments.shipments.update',
  SHIPMENTS_DELETE: 'shipments.shipments.delete',
  SHIPMENTS_STATUS_MANAGE: 'shipments.status.manage',
  SHIPMENTS_TRACKING_MANAGE: 'shipments.tracking.manage',
  DOCUMENTS_VIEW: 'documents.documents.view',
  DOCUMENTS_UPLOAD: 'documents.documents.upload',
  DOCUMENTS_DOWNLOAD: 'documents.documents.download',
  DOCUMENTS_DELETE: 'documents.documents.delete',
  DOCUMENTS_GENERATED_CREATE: 'documents.generated.create',
  FINANCE_INVOICES_VIEW: 'finance.invoices.view',
  FINANCE_INVOICES_CREATE: 'finance.invoices.create',
  FINANCE_INVOICES_UPDATE: 'finance.invoices.update',
  FINANCE_INVOICES_DELETE: 'finance.invoices.delete',
  FINANCE_SUPPLIER_INVOICES_VIEW: 'finance.supplier_invoices.view',
  FINANCE_SUPPLIER_INVOICES_MANAGE: 'finance.supplier_invoices.manage',
  FINANCE_PAYMENTS_VIEW: 'finance.payments.view',
  FINANCE_PAYMENTS_MANAGE: 'finance.payments.manage',
  FINANCE_EXPENSES_VIEW: 'finance.expenses.view',
  FINANCE_EXPENSES_MANAGE: 'finance.expenses.manage',
  FINANCE_CREDIT_NOTES_MANAGE: 'finance.credit_notes.manage',
  FINANCE_EXCHANGE_RATES_MANAGE: 'finance.exchange_rates.manage',
  FINANCE_BUY_PRICES_VIEW: 'finance.buy_prices.view',
  FINANCE_MARGINS_VIEW: 'finance.margins.view',
  FINANCE_PROFITABILITY_VIEW: 'finance.profitability.view',
  FINANCE_REPORTS_VIEW: 'finance.reports.view',
  FINANCE_REPORTS_EXPORT: 'finance.reports.export',
  REPORTS_DASHBOARD_VIEW: 'reports.dashboard.view',
  REPORTS_OPERATIONAL_VIEW: 'reports.operational.view',
  REPORTS_OPERATIONAL_EXPORT: 'reports.operational.export',
  SEARCH_TENANT_USE: 'search.tenant.use',
  SETTINGS_COMPANY_VIEW: 'settings.company.view',
  SETTINGS_COMPANY_MANAGE: 'settings.company.manage',
  SETTINGS_NOTIFICATIONS_MANAGE: 'settings.notifications.manage',
  SUPPORT_COMPANY_REQUESTS_VIEW: 'support.company_requests.view',
  SUPPORT_COMPANY_REQUESTS_MANAGE: 'support.company_requests.manage',
  SUPPORT_RAANKO_TICKETS_VIEW: 'support.raanko_tickets.view',
  SUPPORT_RAANKO_TICKETS_CREATE: 'support.raanko_tickets.create',
  IMPORTS_JOBS_VIEW: 'imports.jobs.view',
  IMPORTS_JOBS_RUN: 'imports.jobs.run',
} as const;

export type PlatformPermission =
  (typeof PlatformPermissions)[keyof typeof PlatformPermissions];
export type TenantPermission =
  (typeof TenantPermissions)[keyof typeof TenantPermissions];

/** All tenant permission keys as a flat list for seeding. */
export const ALL_TENANT_PERMISSION_KEYS: string[] = Object.values(
  TenantPermissions,
);

/** Feature entitlement keys (plan catalog). */
export const FeatureKeys = {
  CRM: 'feature.crm',
  SUPPLIERS: 'feature.suppliers',
  QUOTES: 'feature.quotes',
  BOOKINGS: 'feature.bookings',
  SHIPMENTS: 'feature.shipments',
  DOCUMENTS: 'feature.documents',
  FINANCE: 'feature.finance',
  REPORTS: 'feature.reports',
  PORTAL: 'feature.portal',
  IMPORTS: 'feature.imports',
  // Future platform modules — never auto-entitled on Trial/Paid MVP seeds
  WAREHOUSE: 'feature.warehouse',
  INVENTORY: 'feature.inventory',
  FLEET: 'feature.fleet',
  GPS_TRACKING: 'feature.gps_tracking',
  DRIVER_APP: 'feature.driver_app',
  CUSTOMER_APP: 'feature.customer_app',
  OPS_APP: 'feature.ops_app',
  CARRIER_API: 'feature.carrier_api',
  AIRLINE_API: 'feature.airline_api',
  WHATSAPP: 'feature.whatsapp',
  SMS: 'feature.sms',
  QUICKBOOKS: 'feature.quickbooks',
  XERO: 'feature.xero',
  PAYMENTS: 'feature.payments',
  ESIGN: 'feature.esign',
  AI_DOCUMENTS: 'feature.ai_documents',
} as const;

export type FeatureKey = (typeof FeatureKeys)[keyof typeof FeatureKeys];
